app/models.py
from flask_login import UserMixin
from .extensions import db  # Importez db à partir de extensions.py
from werkzeug.security import check_password_hash, generate_password_hash
from .extensions import db  # Importez db à partir de extensions.py

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password = db.Column(db.String(256))  # Augmenté de 128 à 256
    address = db.Column(db.String(128), nullable=True)
    hobbies = db.Column(db.String(128), nullable=True)
    skills = db.Column(db.String(128), nullable=True)
    profile_pic_url = db.Column(db.String(256), nullable=True)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def __repr__(self):
        return f'<User {self.username}>'


class Property(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    description = db.Column(db.Text, nullable=False)
    location = db.Column(db.String(100), nullable=False)
    price = db.Column(db.Float, nullable=False)
    image_url = db.Column(db.String(255), nullable=False)

    def to_dict(self):
        return {
            'id': self.id,
            'title': self.title,
            'description': self.description,
            'location': self.location,
            'price': self.price,
            'image_url': self.image_url
        }

app/__init__.py
import os
from flask import Flask
from flask_restful import Api
from app.models import User, Property
from config import Config
from .extensions import db, migrate, login  # Importez les extensions à partir de extensions.py

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    app.secret_key = 'allezol69latrick'
    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)

    login.login_view = 'main.connexion'

    app.config['UPLOAD_FOLDER'] = os.path.join(app.root_path, 'static/uploads')
    app.add_url_rule('/uploads/<filename>', 'uploaded_file', build_only=True)
    app.static_folder = 'static'

    from app.routes import main as main_blueprint
    app.register_blueprint(main_blueprint)



    return app

@login.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/routes.py
import os
import re  # Ajouté pour la validation de l'email et du mot de passe
from flask import Blueprint, app, current_app, jsonify, render_template, request, redirect, url_for, flash
from flask_login import login_user, login_required, current_user, logout_user
from app import db
from app.models import User
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename  # Import secure_filename
from app.models import Property

main = Blueprint('main', __name__)

@main.route('/')
def index():
    properties = Property.query.all()
    return render_template('index.html', properties=properties)

@main.route('/users')
def users():
    users = User.query.all()
    return render_template('users.html', users=users)

@main.route('/add_user', methods=['POST'])
def add_user():
    username = request.form['username']
    email = request.form['email']
    new_user = User(username=username, email=email)
    db.session.add(new_user)
    db.session.commit()
    return redirect(url_for('main.users'))

@main.route('/users', methods=['GET'])
def get_users():
    users = User.query.all()
    users_list = [{'id': user.id, 'username': user.username, 'email': user.email} for user in users]
    return jsonify(users_list)

@main.route('/connexion', methods=['GET', 'POST'])
def connexion():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        user = User.query.filter_by(email=email).first()
        if user and user.check_password(password):
            login_user(user)
            flash('Login successful!', 'success')
            return redirect(url_for('main.index'))
        else:
            flash('Invalid email or password', 'danger')
    return render_template('connexion.html')


@main.route('/profile')
@login_required
def profile():
    return render_template('profile.html', user=current_user)

def is_email_valid(email):
    regex = r'^\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
    return re.match(regex, email)

def is_password_valid(password):
    # Minimum une majuscule, un caractère spécial, et au moins 8 caractères
    regex = r'^(?=.*[A-Z])(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$'
    return re.match(regex, password)

@main.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        password = request.form['password']

        if not is_email_valid(email):
            flash('Email invalide. Veuillez entrer un email valide.')
            return redirect(url_for('main.register'))

        if not is_password_valid(password):
            flash('Le mot de passe doit contenir au moins une majuscule, un caractère spécial et être d\'au moins 8 caractères.')
            return redirect(url_for('main.register'))

        hashed_password = generate_password_hash(password, method='pbkdf2:sha256', salt_length=8)
        new_user = User(username=username, email=email, password=hashed_password)

        try:
            db.session.add(new_user)
            db.session.commit()
            return redirect(url_for('main.connexion'))
        except Exception as e:
            db.session.rollback()
            flash('Erreur lors de l\'enregistrement. Veuillez réessayer.')
            print(e)
            return redirect(url_for('main.register'))

    return render_template('connexion.html')

@main.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'info')
    return redirect(url_for('main.index'))

@main.route('/upload_profile_pic', methods=['POST'])
@login_required
def upload_profile_pic():
    if 'profile_pic' not in request.files:
        flash('No file part')
        return redirect(url_for('main.profile'))

    file = request.files['profile_pic']
    if file.filename == '':
        flash('No selected file')
        return redirect(url_for('main.profile'))

    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        file_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)

        # Vérifiez et créez le dossier uploads si nécessaire
        os.makedirs(os.path.dirname(file_path), exist_ok=True)

        file.save(file_path)
        current_user.profile_pic_url = url_for('static', filename=f'uploads/{filename}')
        db.session.commit()
        flash('Profile picture updated successfully.')
        return redirect(url_for('main.profile'))

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in {'png', 'jpg', 'jpeg', 'gif'}





@main.route('/update_profile', methods=['POST'])
@login_required
def update_profile():
    data = request.get_json()
    current_app.logger.info(f"Received data for update: {data}")

    if 'username' in data:
        current_app.logger.info(f"Updating username: {data['username']}")
        current_user.username = data['username']
    if 'email' in data:
        current_app.logger.info(f"Updating email: {data['email']}")
        current_user.email = data['email']
    if 'address' in data:
        current_app.logger.info(f"Updating address: {data['address']}")
        current_user.address = data['address']
    if 'hobbies' in data:
        current_app.logger.info(f"Updating hobbies: {data['hobbies']}")
        current_user.hobbies = data['hobbies']
    if 'skills' in data:
        current_app.logger.info(f"Updating skills: {data['skills']}")
        current_user.skills = data['skills']

    try:
        db.session.commit()
        current_app.logger.info("Profile updated successfully")
        return jsonify({'success': True})
    except Exception as e:
        db.session.rollback()
        current_app.logger.error(f"Error updating profile: {e}")
        return jsonify({'success': False, 'error': str(e)})


@main.route('/api/properties', methods=['GET'])
def get_properties():
    properties = Property.query.all()
    properties_list = [{'id': prop.id, 'title': prop.title, 'location': prop.location, 'price': prop.price, 'image_url': prop.image_url, 'description': prop.description} for prop in properties]
    return jsonify(properties_list)

app/templates/admin.html
<!-- admin.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Page</title>
</head>
<body>
    <h1>Welcome to the Admin Page</h1>
</body>
</html>

app/templates/connexion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='conn2.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700;800&display=swap" rel="stylesheet">
</head>
<body>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul class="flashes">
            {% for category, message in messages %}
                <li class="{{ category }}">{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
    <div class="main">
        <div class="container a-container" id="a-container">
            <form id="a-form" class="form" method="POST" action="{{ url_for('main.register') }}">
                <h2 class="form_title title">Créer un compte</h2>
                <div class="form__icons">
                    <!-- Images des icônes -->
                </div>
                <span class="form__span"></span>
                <input class="form__input" type="text" name="username" placeholder="Prénom" required>
                <input class="form__input" type="email" name="email" placeholder="Email" required>
                <input class="form__input" type="password" name="password" placeholder="Mot de Passe" required>
                <button class="form__button button submit" type="submit">S'INSCRIRE</button>
            </form>
        </div>

        <div class="container b-container" id="b-container">
            <form id="b-form" class="form" method="POST" action="{{ url_for('main.connexion') }}">
                <h2 class="form_title title">Connectez-vous au site Web</h2>
                <div class="form__icons">
                    <!-- Images des icônes -->
                </div>
                <span class="form__span"></span>
                <input class="form__input" type="email" name="email" placeholder="Email" required>
                <input class="form__input" type="password" name="password" placeholder="Mot de Passe" required>
                <a class="form__link" href="#">Mot de Passe oublié?</a>
                <button class="form__button button submit" type="submit">SE CONNECTER</button>
            </form>
        </div>
        <div class="switch" id="switch-cnt">
            <div class="switch__circle"></div>
            <div class="switch__circle switch__circle--t"></div>
            <div class="switch__container" id="switch-c1">
                <h2 class="switch__title title">De retour !</h2>
                <p class="switch__description description">Pour rester en contact avec nous, veuillez vous connecter avec vos informations personnelles</p>
                <button class="switch__button button switch-btn">SE CONNECTER</button>
            </div>
            <div class="switch__container is-hidden" id="switch-c2">
                <h2 class="switch__title title">Bienvenue !</h2>
                <p class="switch__description description">Entrez vos informations personnelles et commencez votre voyage avec nous</p>
                <button class="switch__button button switch-btn">S'INSCRIRE</button>
            </div>
        </div>
    </div>
    <script src="{{ url_for('static', filename='conn2.js') }}"></script>
</body>
</html>

app/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='profil.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700;800&display=swap" rel="stylesheet">
</head>
<body>
    <div class="main">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul class="flashes">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}
        <div class="profile-header">
            <div class="profile-picture">
                <form id="profile-pic-form" action="{{ url_for('main.upload_profile_pic') }}" method="POST" enctype="multipart/form-data">
                    <input type="file" id="profile_pic_input" name="profile_pic" style="display:none;" onchange="document.getElementById('profile-pic-form').submit()">
                    <img src="{{ current_user.profile_pic_url or url_for('static', filename='uploads/default.png') }}" alt="Profile Picture" width="100" height="100" onclick="document.getElementById('profile_pic_input').click()">
                </form>
            </div>
            <div class="profile-info">
                <h1>{{ current_user.username }}</h1>
                <p>Woa User</p>
            </div>
            <div class="logout">
                <a href="{{ url_for('main.logout') }}">
                    <button>Logout</button>
                </a>
            </div>
        </div>


        <div class="card">
            <div class="card-header">
                <h2>IDENTITY</h2>
            </div>
            <div class="card-body">
                <table>
                    <tbody>
                        <tr>
                            <td>Name</td>
                            <td>:</td>
                            <td data-field="username">{{ current_user.username }}</td>
                            <td><button onclick="editField(this)">✏️</button></td>
                        </tr>
                        <tr>
                            <td>Email</td>
                            <td>:</td>
                            <td data-field="email">{{ current_user.email }}</td>
                            <td><button onclick="editField(this)">✏️</button></td>
                        </tr>
                        <tr>
                            <td>Address</td>
                            <td>:</td>
                            <td data-field="address">{{ current_user.address or 'None' }}</td>
                            <td><button onclick="editField(this)">✏️</button></td>
                        </tr>
                        <tr>
                            <td>Hobbies</td>
                            <td>:</td>
                            <td data-field="hobbies">{{ current_user.hobbies or 'None' }}</td>
                            <td><button onclick="editField(this)">✏️</button></td>
                        </tr>
                        <tr>
                            <td>Skill</td>
                            <td>:</td>
                            <td data-field="skills">{{ current_user.skills or 'None' }}</td>
                            <td><button onclick="editField(this)">✏️</button></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <h2>RESERVATIONS ❤️</h2>
            </div>
            <div class="card-body">
                <!-- User's reservations content -->
            </div>
        </div>
    </div>

    <script>

async function fetchProperties() {
        try {
            const response = await fetch('/api/properties');
            const properties = await response.json();
            const cardsArea = document.getElementById('cards-area');
            const like = window.localStorage.getItem("like")

            properties.forEach(property => {
                if (like.includes(property.id)) {


                const cardWrapper = document.createElement('div');
                cardWrapper.className = 'card-wrapper main-card';

                const card = document.createElement('a');
                card.className = 'card cardItemjs';
                card.onclick = function() {
                    openModal();
                    document.querySelector("#picturezoom").src  = property.image_url;
                    document.querySelector("#descriptionzoom").innerHTML = property.description;
                    window.localStorage.setItem("selected_id",property.id)
                };

                const cardImageWrapper = document.createElement('div');
                cardImageWrapper.className = 'card-image-wrapper';

                const img = document.createElement('img');
                img.src = property.image_url;
                img.alt = 'Property Image';

                const cardInfo = document.createElement('div');
                cardInfo.className = 'card-info';

                const cardTextBig = document.createElement('div');
                cardTextBig.className = 'card-text big cardText-js';
                cardTextBig.textContent = property.title;

                const cardTextSmallLocation = document.createElement('div');
                cardTextSmallLocation.className = 'card-text small';
                cardTextSmallLocation.textContent = property.location;

                const cardTextSmallPrice = document.createElement('div');
                cardTextSmallPrice.className = 'card-text small';
                cardTextSmallPrice.innerHTML = `Starts from: <span class="card-price">$${property.price}</span>`;

                cardImageWrapper.appendChild(img);
                cardInfo.appendChild(cardTextBig);
                cardInfo.appendChild(cardTextSmallLocation);
                cardInfo.appendChild(cardTextSmallPrice);
                card.appendChild(cardImageWrapper);
                card.appendChild(cardInfo);
                cardWrapper.appendChild(card);
                cardsArea.appendChild(cardWrapper);
            }});
        } catch (error) {
            console.error('Error fetching properties:', error);
        }
    }

    document.addEventListener('DOMContentLoaded', fetchProperties);


        function editField(button) {
            const td = button.parentElement.previousElementSibling;
            const value = td.textContent.trim();
            const input = document.createElement('input');
            input.type = 'text';
            input.value = value;
            td.textContent = '';
            td.appendChild(input);

            button.textContent = 'Save';
            button.onclick = function() { saveField(td, button) };
        }

        function saveField(td, button) {
            const input = td.firstElementChild;
            const value = input.value.trim();
            const field = td.getAttribute('data-field');

            console.log(`Saving field: ${field} with value: ${value}`);

            const data = {};
            data[field] = value;

            fetch("{{ url_for('main.update_profile') }}", {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(data),
            })
            .then(response => response.json())
            .then(result => {
                if (result.success) {
                    alert('Profile updated successfully');
                    td.textContent = value;
                    button.textContent = '✏️';
                    button.onclick = function() { editField(button) };
                } else {
                    alert('Error updating profile');
                }
            });
        }
    </script>

</body>
</html>

app/templates/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Users</title>
</head>
<body>
    <h1>Users List</h1>
    <ul>
        {% for user in users %}
            <li>{{ user.username }} - {{ user.email }}</li>
        {% endfor %}
    </ul>
    <h2>Add User</h2>
    <form action="{{ url_for('add_user') }}" method="post">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username">
        <label for="email">Email:</label>
        <input type="email" id="email" name="email">
        <button type="submit">Add User</button>
    </form>
</body>
</html>

app/templates/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Users List</title>
</head>
<body>
    <h1>Users List</h1>
    <ul>
        {% for user in users %}
        <li>{{ user.username }} - {{ user.email }}</li>
        {% endfor %}
    </ul>
</body>
</html>